export const GithubActionTypes = {
    USERS_GITHUB_REQUEST: 'USERS_GITHUB_REQUEST',
    USERS_GITHUB_RECEIVED: 'USERS_GITHUB_RECEIVED',
    USERS_GITHUB_ERROR: 'USERS_GITHUB_ERROR',
    USERS_GITHUB_LUNCH: 'USERS_GITHUB_LUNCH',

    REPOS_GITHUB_REQUEST: 'REPOS_GITHUB_REQUEST',
    REPOS_GITHUB_RECEIVED: 'REPOS_GITHUB_RECEIVED',
    REPOS_GITHUB_ERROR: 'REPOS_GITHUB_ERROR',
    REPOS_GITHUB_LUNCH: 'REPOS_GITHUB_LUNCH',

    FOLLOWERS_GITHUB_REQUEST: 'FOLLOWERS_GITHUB_REQUEST',
    FOLLOWERS_GITHUB_RECEIVED: 'FOLLOWERS_GITHUB_RECEIVED',
    FOLLOWERS_GITHUB_ERROR: 'FOLLOWERS_GITHUB_ERROR',
    FOLLOWERS_GITHUB_LUNCH: 'FOLLOWERS_GITHUB_LUNCH',
};