export default [
  {
    login: "Greg2a",
    id: 5107832,
    node_id: "MDQ6VXNlcjUxMDc4MzI=",
    avatar_url: "https://avatars.githubusercontent.com/u/5107832?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Greg2a",
    html_url: "https://github.com/Greg2a",
    followers_url: "https://api.github.com/users/Greg2a/followers",
    following_url: "https://api.github.com/users/Greg2a/following{/other_user}",
    gists_url: "https://api.github.com/users/Greg2a/gists{/gist_id}",
    starred_url: "https://api.github.com/users/Greg2a/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Greg2a/subscriptions",
    organizations_url: "https://api.github.com/users/Greg2a/orgs",
    repos_url: "https://api.github.com/users/Greg2a/repos",
    events_url: "https://api.github.com/users/Greg2a/events{/privacy}",
    received_events_url: "https://api.github.com/users/Greg2a/received_events",
    type: "User",
    site_admin: false
  },
  {
    login: "mykbas",
    id: 18208206,
    node_id: "MDQ6VXNlcjE4MjA4MjA2",
    avatar_url: "https://avatars.githubusercontent.com/u/18208206?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/mykbas",
    html_url: "https://github.com/mykbas",
    followers_url: "https://api.github.com/users/mykbas/followers",
    following_url: "https://api.github.com/users/mykbas/following{/other_user}",
    gists_url: "https://api.github.com/users/mykbas/gists{/gist_id}",
    starred_url: "https://api.github.com/users/mykbas/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/mykbas/subscriptions",
    organizations_url: "https://api.github.com/users/mykbas/orgs",
    repos_url: "https://api.github.com/users/mykbas/repos",
    events_url: "https://api.github.com/users/mykbas/events{/privacy}",
    received_events_url: "https://api.github.com/users/mykbas/received_events",
    type: "User",
    site_admin: false
  }
];
